export type AssetRequirement = {
  slug: string;
  asset: string;
  requiredFor: string[];
  status: "needed" | "confirmed-available" | "permission-required" | "deferred";
  purpose: string;
  acceptance: string;
};

export const assetContentRequirements: AssetRequirement[] = [
  { slug: "parent-brand-identity", asset: "Luxe Event Co. logo and wordmark files", requiredFor: ["/"], status: "confirmed-available", purpose: "Primary brand identity, metadata, and social preview consistency.", acceptance: "Approved light/dark variants, SVG or high-resolution raster, and usage guidance." },
  { slug: "division-identities", asset: "Luxe Coffee Bar, Luxe Sweet Cart, and Luxe Seating Rentals identities", requiredFor: ["/experiences", "/experiences/coffee-bar", "/experiences/sweet-cart", "/experiences/seating-rentals"], status: "needed", purpose: "Keep divisions individually recognizable within the parent system.", acceptance: "Approved logos, marks, colours, and minimum-size/contrast guidance." },
  { slug: "home-hero-media", asset: "Coffee, Sweet Cart, Seating Rentals, and cohesive all-brand hero films with posters", requiredFor: ["/"], status: "needed", purpose: "Complete the approved four-stage Home cinematic sequence without withholding copy or actions.", acceptance: "Four permission-cleared muted films, mobile-safe posters, captions or adjacent alternatives if any film becomes meaningful, and optimized MP4/WebM sources." },
  { slug: "coffee-photography", asset: "Original Coffee Bar event photography", requiredFor: ["/", "/experiences/coffee-bar", "/events/weddings", "/events/corporate-events", "/events/brand-activations"], status: "needed", purpose: "Show cart, barista service, drinks, guest interaction, and real event context.", acceptance: "Permission-cleared originals with event context, location, date, and alt-text notes." },
  { slug: "sweet-photography", asset: "Original Sweet Cart event photography", requiredFor: ["/", "/experiences/sweet-cart", "/events/weddings", "/events/baby-showers", "/events/bridal-showers", "/events/birthdays"], status: "needed", purpose: "Show on-site preparation, carts, toppings, presentation, and guest interaction.", acceptance: "Permission-cleared originals with menu/event context and alt-text notes." },
  { slug: "seating-photography", asset: "Original Seating Rentals photography", requiredFor: ["/", "/experiences/seating-rentals", "/gallery", "/events/weddings", "/events/corporate-events"], status: "needed", purpose: "Show inventory, room structure, styling, and setup quality.", acceptance: "Permission-cleared originals with item names, dimensions where relevant, and event context." },
  { slug: "event-page-photography", asset: "Original, permission-cleared media for every event page", requiredFor: ["/events/weddings", "/events/corporate-events", "/events/brand-activations", "/events/baby-showers", "/events/bridal-showers", "/events/birthdays", "/events/private-events", "/gallery"], status: "needed", purpose: "Give each event journey first-hand visual evidence instead of reusing generic division imagery.", acceptance: "At least one approved visual story per represented event context with accurate service, event, location, caption, and alt-text metadata." },
  { slug: "branded-activation-proof", asset: "Approved branded cups, menus, signage, cart-wrap, and activation examples", requiredFor: ["/events/brand-activations", "/events/corporate-events"], status: "permission-required", purpose: "Prove corporate and agency customization capability.", acceptance: "Client/brand permissions, campaign context, production notes, and approved usage." },
  { slug: "corporate-organization-logos", asset: "Approved OPTrust, CST Savings, Convergint, ICNA Canada, and Waste Connections of Canada logo files", requiredFor: ["/", "/events/corporate-events", "/events/brand-activations"], status: "confirmed-available", purpose: "Provide restrained, approved organization proof for professional buyers.", acceptance: "Use the approved local files without changing proportions or implying endorsement, partnership, testimonial, or case-study approval." },
  { slug: "corporate-proof", asset: "Approved corporate testimonials and case-study details", requiredFor: ["/events/corporate-events", "/events/brand-activations"], status: "permission-required", purpose: "Support trust with operationally specific first-hand evidence.", acceptance: "Written permission for each quotation, attribution, event detail, outcome, campaign reference, and associated image." },
  { slug: "wedding-proof", asset: "Approved wedding testimonials, venue context, and photography", requiredFor: ["/events/weddings", "/experiences/coffee-bar", "/experiences/sweet-cart", "/gallery"], status: "permission-required", purpose: "Support couples, planners, venues, and coordinators.", acceptance: "Permission-cleared images and testimonials with accurate attribution." },
  { slug: "menu-content", asset: "Final menu availability, dietary notes, and version ownership", requiredFor: ["/experiences/coffee-bar", "/experiences/sweet-cart", "/faq"], status: "needed", purpose: "Complete the currently published confirmed drink, dessert, sauce, and topping selections with final operating guidance.", acceptance: "Final availability, dietary notes, effective date, and internal content owner." },
  { slug: "operational-proof", asset: "Setup dimensions, service windows, staffing, power/water, outdoor, delivery, and teardown information", requiredFor: ["/experiences/coffee-bar", "/experiences/sweet-cart", "/experiences/seating-rentals", "/faq", "/contact"], status: "deferred", purpose: "Answer the practical questions that distinguish Luxe from generic providers.", acceptance: "Client-approved operational specification for each division." },
  { slug: "rental-inventory-and-policies", asset: "Confirmed rental inventory, quantities, delivery area, setup, teardown, damage, weather, and outdoor policies", requiredFor: ["/experiences/seating-rentals", "/events/weddings", "/events/corporate-events", "/faq", "/contact"], status: "deferred", purpose: "Support accurate rental planning without turning the page into an unsupported catalogue.", acceptance: "Client-approved inventory register and policy language with effective date and internal owner." },
  { slug: "gallery-taxonomy", asset: "Gallery taxonomy and metadata for each image group", requiredFor: ["/gallery"], status: "needed", purpose: "Connect images to divisions, event types, locations, and related pages.", acceptance: "Stable image IDs, alt text, captions, permissions, associated paths, and filters." },
  { slug: "testimonial-content", asset: "Approved wedding and corporate testimonial quotations", requiredFor: ["/", "/events/weddings", "/events/corporate-events"], status: "permission-required", purpose: "Complete reserved testimonial placements with credible first-hand proof.", acceptance: "Approved wording, attribution, service and event context, publication permission, and any required privacy treatment." },
  { slug: "inquiry-platform", asset: "Production third-party inquiry URL, return behavior, minimum-booking guidance, and privacy context", requiredFor: ["/contact"], status: "deferred", purpose: "Complete the qualified handoff without duplicating operational booking functionality.", acceptance: "Approved production URL, destination host, tracking boundary, consent/privacy copy, fallback behavior, and confirmation-return decision." },
  { slug: "social-preview-assets", asset: "Approved Open Graph, square Google thumbnail, favicon, and social avatar assets", requiredFor: ["/"], status: "confirmed-available", purpose: "Consistent sharing and search-result presentation.", acceptance: "High-resolution, legible assets with transparent/background variants as needed." },
];

export const assetRules = [
  "Do not use stock photography as proof of Luxe work.",
  "Do not publish a client, logo, testimonial, venue, or event image without permission.",
  "Every meaningful image must have accurate alt text and, when relevant, event/division metadata.",
  "Visible claims, image captions, metadata, and structured data must agree.",
] as const;
