export const visualSystem = {
  status: "established",
  governingSources: [
    "Luxe Event Co. Website Strategy, Design, Development, SEO and AEO Implementation Master Specification",
    "Luxe Brands client intake form, formatted July 2026",
  ],
  creativeDirection: {
    name: "Editorial Event Portfolio",
    intent:
      "Present Luxe Event Co. as a composed portfolio of hospitality experiences, not a service catalogue or product grid.",
    qualities: [
      "bright",
      "elegant",
      "timeless",
      "corporate-friendly",
      "trend-aware",
      "editorial",
      "high-end",
    ],
    redLines: [
      "generic beige-and-gold luxury templates",
      "catalogue-style product grids",
      "excessive cards",
      "stock-looking event imagery",
      "constant promotional messaging",
      "motion used as spectacle",
      "gold as a dominant surface or paragraph colour",
    ],
  },
  colour: {
    foundation: {
      ivory: { value: "#F8F6F2", role: "Primary page surface and negative space" },
      champagneGold: { value: "#C8A97E", role: "Decorative accent, rules, key shapes, and large display details" },
      matteBlack: { value: "#1F1F1F", role: "Primary text, dark surfaces, and high-contrast controls" },
      softTaupe: { value: "#D8CEC3", role: "Secondary surfaces, material warmth, and image-adjacent fields" },
      warmGrey: { value: "#7A7A7A", role: "Large secondary text, metadata, icons, and non-essential detail" },
    },
    accessibleText: {
      primary: { value: "#1F1F1F", onIvoryContrast: 15.27 },
      secondary: { value: "#595754", onIvoryContrast: 6.67, onTaupeContrast: 4.64 },
      goldInk: {
        value: "#695438",
        onIvoryContrast: 6.65,
        onTaupeContrast: 4.63,
        note:
          "Use for small accent copy on light surfaces.",
      },
      goldOnDark: {
        value: "#DEC297",
        onWarmDarkContrast: 5.08,
        onMatteBlackContrast: 9.63,
        note: "Use for small gold-toned copy on dark surfaces.",
      },
    },
    rules: [
      "Ivory is the default page field.",
      "Matte black carries body copy and functional contrast.",
      "Champagne gold is an accent, never a dominant background or paragraph colour.",
      "Warm grey is not used for small essential text on ivory because its contrast is below 4.5:1.",
      "Division identity is expressed through imagery, crop, material, shape, and composition before additional colour.",
    ],
    surfaceRhythm: {
      roles: {
        canvas: "Ivory grid field for orientation, reading, and negative space.",
        narrative:
          "Taupe-blended full-bleed field for parent-brand explanation, testimonials, and quieter editorial chapters.",
        soft:
          "Lighter taupe-blended field for connected choices, combinations, or supporting transitions.",
        emphasis:
          "Matte-black full-bleed field for decisive brand statements, operational proof, and selected conversion moments.",
        visual:
          "Photography or video-led field whose contrast is controlled by media treatment and local copy surfaces.",
      },
      sequencingRules: [
        "Every permanent page uses a deliberate sequence of canvas, narrative, soft, emphasis, and visual fields rather than one continuous ivory surface.",
        "Surface changes create meaningful chapters; they are not applied as automatic alternating stripes.",
        "Matte-black chapters are reserved for high-value information and should not appear back-to-back.",
        "Taupe chapters separate narrative or proof contexts without competing with photography.",
        "Full-bleed surfaces keep headings, body copy, controls, and evidence aligned to the shared content grid.",
        "Champagne gold remains an accent on every surface and never becomes the contrast strategy by itself.",
        "Dark chapters use ivory primary copy, muted ivory secondary copy, and translucent ivory rules.",
        "Each page blueprint must name its intended surface sequence before implementation.",
      ],
    },
  },
  typography: {
    display: {
      family: "Manrope",
      fallback: "sans-serif",
      use: "Major headings and high-impact narrative moments through display scale, weight, and composition",
      weights: [500, 600],
      rationale:
        "A unified family keeps the parent identity, headings, body copy, and interface language visually connected.",
    },
    body: {
      family: "Manrope",
      fallback: "sans-serif",
      use: "Body copy, navigation, labels, controls, metadata, and functional information",
      weights: [400, 500, 600],
    },
    wordmark: {
      family: "Manrope",
      rule: "The approved Luxe Event Co. wordmark treatment remains distinct from editorial page headings.",
    },
    scale: {
      displayXl: "clamp(3.6rem, 9vw, 9.5rem)",
      displayLg: "clamp(3rem, 6.4vw, 7rem)",
      internalPageHero: "clamp(3.45rem, 4.35vw, 5.3rem)",
      internalPageHeroMobile: "clamp(1.52rem, 7.65vw, 3rem)",
      headingLg: "clamp(2.25rem, 4.5vw, 4.75rem)",
      headingMd: "clamp(1.75rem, 3vw, 3rem)",
      headingSm: "clamp(1.35rem, 1.8vw, 1.8rem)",
      bodyLead: "clamp(1.125rem, 1.5vw, 1.375rem)",
      body: "clamp(1rem, 0.4vw + 0.92rem, 1.125rem)",
      small: "0.875rem",
      label: "0.75rem",
    },
    measures: {
      displayHeading: "14ch",
      sectionHeading: "18ch",
      lead: "48ch",
      body: "66ch",
    },
    tracking: {
      displayXl: "-0.055em",
      displayLg: "-0.08em",
      headingLg: "-0.055em",
      headingMd: "-0.04em",
      body: "normal",
      labels: "0.12em to 0.18em",
    },
    rules: [
      "Only one display-level heading should dominate a viewport.",
      "Every internal-page H1 follows the Weddings scale, weight, line height, and tracking; the Home hero is the sole exception.",
      "Primary section headings must not exceed the internal-page hero scale and should use its weight, line height, and tracking unless a smaller hierarchy is more appropriate.",
      "Signature internal-page headings use two or three intentional desktop lines and never wrap to a fourth line.",
      "Other headings wrap naturally and must remain readable without art-directed breaks.",
      "Body copy does not exceed 66 characters per line.",
      "Uppercase labels are short, semantically secondary, and never used for paragraphs.",
      "No essential text is rendered below 14px.",
    ],
  },
  spacing: {
    baseUnit: "4px",
    scale: ["4px", "8px", "12px", "16px", "24px", "32px", "48px", "64px", "96px", "128px"],
    sectionGap: "clamp(80px, 10vw, 160px)",
    pageInline: "clamp(22px, 5vw, 76px)",
    rules: [
      "Section spacing creates hierarchy rather than empty filler.",
      "Whitespace must balance the composition above, below, and around focal content.",
      "Related labels, headings, copy, and actions use progressively tighter spacing.",
      "Mobile spacing is recomposed by hierarchy, not reduced by one universal multiplier.",
    ],
  },
  layout: {
    maxWidth: "1440px",
    readingWidth: "672px",
    grid: {
      desktop: "12-column editorial grid",
      tablet: "8-column editorial grid",
      mobile: "4-column compositional grid",
      gap: "clamp(16px, 2.2vw, 40px)",
    },
    principles: [
      "Photography leads service and event storytelling.",
      "Asymmetry must support hierarchy and movement through content.",
      "Full-width visual moments are balanced by concise reading-width copy.",
      "Image crops are selected by subject, service, event, and breakpoint.",
      "Cards are reserved for true peer choices, not used as the default section container.",
      "Layering may connect photography, typography, rules, and material fields without obscuring content.",
      "Section boundaries remain perceptible through spacing, crop changes, rules, or surface shifts.",
    ],
    responsiveRules: [
      "Desktop compositions do not simply shrink.",
      "Tablet preserves hierarchy while reducing simultaneous focal points.",
      "Mobile reorders content according to decision priority and touch flow.",
      "Landscape and short-height layouts reduce decorative space before reducing readable type.",
      "Ultra-wide layouts cap reading and content width while allowing selected imagery to bleed.",
      "No focal subject may depend on a single fixed-position crop across breakpoints.",
    ],
    photographyRules: [
      "Use first-party event photography wherever possible.",
      "Prioritize hospitality, interaction, finish, and environment over isolated product inventory.",
      "Coffee imagery emphasizes craft, warmth, and service atmosphere.",
      "Dessert imagery emphasizes live preparation, indulgence, and presentation.",
      "Seating imagery emphasizes architecture, layout, material, and completed rooms.",
      "Avoid generic stock scenes and repetitive catalogue cutouts.",
    ],
  },
  motion: {
    durations: {
      fast: "180ms",
      standard: "320ms",
      reveal: "700ms",
      slow: "1000ms",
      ambient: "16000ms",
    },
    easing: {
      out: "cubic-bezier(0.22, 1, 0.36, 1)",
      standard: "cubic-bezier(0.4, 0, 0.2, 1)",
    },
    permitted: [
      "controlled image reveals",
      "subtle section transitions",
      "responsive hover and focus states",
      "menu transitions",
      "gentle image movement",
      "experience-selector interaction",
    ],
    constraints: [
      "Content is present in server-rendered HTML and never gated by motion.",
      "Motion uses opacity and transform rather than layout-changing properties.",
      "No animation delays reading, navigation, or conversion actions.",
      "No required content depends on hover or interaction to become available.",
      "Animation density is limited to one primary motion idea per section.",
      "Parallax and continuous movement require explicit review before use.",
      "prefers-reduced-motion removes non-essential movement and smooth scrolling.",
    ],
  },
  accessibility: {
    target: "WCAG 2.2 Level AA",
    rules: [
      "Every page provides semantic landmarks, one logical H1, and a skip-to-content link.",
      "Body text maintains at least 4.5:1 contrast.",
      "Large text and meaningful graphical controls maintain at least 3:1 contrast.",
      "Keyboard focus is always visible and is not communicated by colour alone.",
      "Navigation, disclosures, filters, and future form controls remain keyboard and screen-reader accessible.",
      "Touch targets are designed to reach at least 44 by 44 CSS pixels.",
      "Decorative imagery has empty alternative text; meaningful imagery receives specific alternative text.",
      "Autoplay media is muted; meaningful video requires captions and an equivalent text alternative.",
      "Dynamic results, errors, and submission outcomes are announced with appropriate status semantics.",
      "Responsive reordering preserves logical source and keyboard order.",
      "Text remains usable at 200% zoom without clipping or horizontal scrolling.",
    ],
  },
  siteContinuity: {
    requiredAcrossPages: [
      "Luxe Event Co. parent-brand hierarchy in the global shell and metadata",
      "fine ivory grid canvas between tonal chapters",
      "the approved typography, tracking, measure, spacing, and rule system",
      "the site-wide surface rhythm and full-bleed chapter behaviour",
      "descriptive internal links and one clear primary CTA per page",
      "contextual inquiry panels rather than repeated generic conversion copy",
      "approved signature modules where the page purpose calls for them",
      "server-rendered meaningful content, visible focus, reduced motion, and responsive recomposition",
      "first-party photography direction and division-specific visual identity",
    ],
    contextualizePerPage: [
      "hero composition and media behaviour",
      "surface sequence and number of contrast chapters",
      "primary and secondary CTA language",
      "proof, testimonials, FAQs, and event-specific content",
      "which signature modules appear and how prominently they are placed",
      "division-specific imagery, crops, inclusions, and operational detail",
    ],
    prohibitions: [
      "copying the Home page section order onto another page",
      "using identical CTA headings on every page",
      "alternating dark and light surfaces mechanically",
      "turning reusable modules into generic cards",
      "reusing proof or claims outside a context where they remain accurate",
    ],
  },
} as const;

export type VisualSystem = typeof visualSystem;
